daraz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    
    path('', include('mainapp.urls')),
    path('', include('product.urls')),
    path('', include('dashboard.urls')),
    path('seller/', include('sell_on_daraz.urls')),
    path('', include('offer.urls')),
    path('', include('flashsale.urls')),
    path('', include('messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    # path('user/dashboard/', views.dashboard, name='dashboard'),
    path('user/manage_ac/', views.manage_ac, name='manage_ac'),
    path('user/my_profile/', views.my_profile, name='my_profile'),
    path('user/inbox/<int:pk>/', views.inbox, name='inbox'),
    path('user/address_book/', views.address_book, name='address_book'),
    path('user/payment_options/', views.payment_options, name='payment_options'),
    path('user/wallet/', views.wallet, name='wallet'),
    path('user/vouchers/', views.vouchers, name='vouchers'),
    path('user/my_orders/', views.my_orders, name='my_orders'),
    path('user/my_returns/', views.my_returns, name='my_returns'),
    path('user/my_cancellations/', views.my_cancellations, name='my_cancellations'),
    path('user/my_reviews/', views.my_reviews, name='my_reviews'),
    path('user/wishlist/', views.wishlist, name='wishlist'),
]

sell_on_daraz/urls.py
from django.urls import path
from . import views

app_name = 'sell_on_daraz'
urlpatterns = [
    path('for_sale/', views.for_sale, name='for_sale'),
    path('inbox/<int:pk>/', views.inbox, name='inbox'),
    path('new_banner/', views.new_banner, name='new_banner'),
    path('new_category/', views.new_category, name='new_category'),
    path('new_sub_category/', views.new_sub_category, name='new_sub_category'),
    path('new_groups/', views.new_groups, name='new_groups'),
    path('new_product/', views.new_product, name='new_product'),
    
    path('<int:pk>/<int:id>/new_brand/', views.new_brand, name='new_brand'),
    path('<int:pk>/<int:id>/new_material/', views.new_material, name='new_material'),
    path('<int:pk>/<int:id>/new_warranty_period/', views.new_warranty_period, name='new_warranty_period'),
    path('<int:pk>/<int:id>/new_listed_year_season/', views.new_listed_year_season, name='new_listed_year_season'),
    path('<int:pk>/<int:id>/new_mens_trend/', views.new_mens_trend, name='new_mens_trend'),
    
    path('load_options/', views.load_options, name='load_options'),
    
    path('banner/<int:pk>/edit/', views.edit_banner, name='edit_banner'),
    path('category/<int:pk>/edit/', views.edit_category, name='edit_category'),
    path('sub_category/<int:pk>/edit/', views.edit_sub_category, name='edit_sub_category'),
    path('group/<int:pk>/edit/', views.edit_group, name='edit_group'),
    path('product/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('product/<int:pk>/manage/', views.manage_product, name='manage_product'),
    
    path('banner/<int:pk>/delete/', views.delete_banner, name='delete_banner'),
    path('category/<int:pk>/delete/', views.delete_category, name='delete_category'),
    path('subcategory/<int:pk>/delete/', views.delete_sub_category, name='delete_sub_category'),
    path('group/<int:pk>/delete/', views.delete_group, name='delete_group'),
    
    path('brand/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_brand, name='delete_brand'),
    path('material/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_material, name='delete_material'),
    path('warranty_period/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_warranty_period, name='delete_warranty_period'),
    path('listed_year_season/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_listed_year_season, name='delete_listed_year_season'),
    path('mens_trend/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_mens_trend, name='delete_mens_trend'),
    
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
]

sell_on_daraz/models.py
from django.db import models

# Create your models here.

sell_on_daraz/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from mainapp.models import Category, SubCategory, Group, Banner
from product.models import Product, Brand, MainMaterial, WarrantyPeriod, ListedYearSeason, MensTrend

from product.forms import NewColorFamily, NewProduct, EditProduct, ManageProduct
from .forms import NewBanner, NewCategory, NewSubCategory, NewGroup, NewBrand, NewMaterial, NewWarrantyPeriod, NewListedYearSeason, NewMensTrend, EditBanner, EditCategory, EditSubCategory, EditGroup

from messaging.models import Conversation, ConversationMessage
from messaging.forms import ConversationMessageForm
# Create your views here.
# .............................Daraz_On_Sale.............................
@login_required
def for_sale(request):
    banners = Banner.objects.all() 
    categories = Category.objects.all() 
    sub_categories = SubCategory.objects.all() 
    groups = Group.objects.all() 
    products = Product.objects.filter(created_by=request.user).filter(is_sold=False) 
    sold_products = Product.objects.filter(created_by=request.user).filter(is_sold=True)
    conversations = Conversation.objects.filter(reciever=request.user)
    context = {
        'banners': banners,
        'categories': categories,
        'sub_categories': sub_categories,
        'groups': groups,
        'products': products,
        'sold_products': sold_products,
        'conversations': conversations,
    }
    return render(request, 'add_new_pages/for_sale.html', context)

@login_required
def inbox(request, pk):
    banners = Banner.objects.all() 
    categories = Category.objects.all() 
    sub_categories = SubCategory.objects.all() 
    groups = Group.objects.all() 
    products = Product.objects.filter(created_by=request.user).filter(is_sold=False) 
    
    sender=request.user
    conversations = Conversation.objects.filter(reciever=request.user)
    if pk>0:
        this_conversation = Conversation.objects.get(id=pk)
    else:
        this_conversation = Conversation.objects.none()
    messages = ConversationMessage.objects.filter(conversation_id=pk)
    form = ConversationMessageForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=False) 
            form.instance.conversation=get_object_or_404(Conversation, pk=pk)
            form.instance.created_by=request.user
            form.save()
            return redirect('.')
    else:
        form = ConversationMessageForm()
        
    context = {
        'banners': banners,
        'categories': categories,
        'sub_categories': sub_categories,
        'groups': groups,
        'products': products,
        'form': form,
        'messages': messages,
        'sender': sender,
        'conversations': conversations,
        'this_conversation': this_conversation,
    }
    return render(request, 'add_new_pages/inbox.html', context)


# ................................................NEW................................................................
@login_required
def new_banner(request):
    banners = Banner.objects.all() 
    categories = Category.objects.all() 
    sub_categories = SubCategory.objects.all() 
    groups = Group.objects.all() 
    products = Product.objects.filter(created_by=request.user).filter(is_sold=False) 
    conversations = Conversation.objects.filter(reciever=request.user)
    banner_form = NewBanner(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if banner_form.is_valid():
            banner = banner_form.save(commit=False)
            banner.created_by = request.user
            banner.save()
            return redirect('sell_on_daraz:new_banner')
    else:
        banner_form = NewBanner()
    context = {
        'banners': banners,
        'categories': categories,
        'sub_categories': sub_categories,
        'groups': groups,
        'products': products,
        'banner_form': banner_form,
        'conversations': conversations,
    }
    return render(request, 'add_new_pages/banners.html', context)

@login_required
def new_category(request):
    banners = Banner.objects.all() 
    categories = Category.objects.all() 
    sub_categories = SubCategory.objects.all() 
    groups = Group.objects.all() 
    products = Product.objects.filter(created_by=request.user).filter(is_sold=False) 
    conversations = Conversation.objects.filter(reciever=request.user)
    category_form = NewCategory(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if category_form.is_valid():
            category = category_form.save(commit=False)
            category.created_by = request.user
            category.save()
            return redirect('sell_on_daraz:new_category')
    else:
        category_form = NewCategory()
    context = {
        'banners': banners,
        'categories': categories,
        'sub_categories': sub_categories,
        'groups': groups,
        'products': products,
        'category_form': category_form,
        'conversations': conversations,
    }
    return render(request, 'add_new_pages/categories.html', context)

@login_required
def new_sub_category(request):
    banners = Banner.objects.all() 
    categories = Category.objects.all() 
    sub_categories = SubCategory.objects.all() 
    groups = Group.objects.all() 
    products = Product.objects.filter(created_by=request.user).filter(is_sold=False) 
    conversations = Conversation.objects.filter(reciever=request.user)
    sub_category_form = NewSubCategory(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if sub_category_form.is_valid():
            sub_category = sub_category_form.save(commit=False)
            sub_category.created_by = request.user
            sub_category.save()
            return redirect('sell_on_daraz:new_sub_category')
    else:
        sub_category_form = NewSubCategory()
    context = {
        'banners': banners,
        'categories': categories,
        'sub_categories': sub_categories,
        'groups': groups,
        'products': products,
        'sub_category_form': sub_category_form,
        'conversations': conversations,
    }
    return render(request, 'add_new_pages/sub_categories.html', context)


@login_required
def new_groups(request):
    banners = Banner.objects.all() 
    categories = Category.objects.all() 
    sub_categories = SubCategory.objects.all() 
    groups = Group.objects.all() 
    products = Product.objects.filter(created_by=request.user).filter(is_sold=False) 
    conversations = Conversation.objects.filter(reciever=request.user)
    new_group_form = NewGroup(request.POST, request.FILES)
    if request.method == 'POST':
        if 'new_group_form' in request.POST:
            if new_group_form.is_valid():
                group = new_group_form.save(commit=False)
                group.created_by = request.user
                group.save()
                return redirect('sell_on_daraz:new_groups')
        else:
            new_group_form = NewGroup()
    context = {
        'banners': banners,
        'categories': categories,
        'sub_categories': sub_categories,
        'groups': groups,
        'products': products,
        'new_group_form': new_group_form,
        'conversations': conversations,
    }
    return render(request, 'add_new_pages/groups.html', context)

@login_required
def load_options(request):
    category_id = request.GET.get('category')
    subcategory_id = request.GET.get('subcategory')
    sub_categories = SubCategory.objects.filter(category_id=category_id)
    groups = Group.objects.filter(subcategory_id=subcategory_id)
    context = {
        'sub_categories': sub_categories,
        'groups': groups,
    }
    return render(request, 'sell_on_daraz/options.html', context)

@login_required
def new_product(request):
    banners = Banner.objects.all() 
    categories = Category.objects.all() 
    sub_categories = SubCategory.objects.all() 
    groups = Group.objects.all() 
    products = Product.objects.filter(created_by=request.user).filter(is_sold=False) 
    conversations = Conversation.objects.filter(reciever=request.user)
    new_product_form = NewProduct(request.POST or None, request.FILES or None)
    new_colorfamily_form = NewColorFamily(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if 'new_product_form' in request.POST:
            if new_product_form.is_valid():
                product = new_product_form.save(commit=False)
                product.created_by = request.user
                product.save()
                return redirect('sell_on_daraz:manage_product', product.id)
        elif 'new_colorfamily_form' in request.POST:
            if new_colorfamily_form.is_valid():
                new_colorfamily_form.save()
                return redirect('sell_on_daraz:new_product')
        else:
            new_product_form = NewProduct()
            new_colorfamily_form = NewColorFamily()
    context = {
        'banners': banners,
        'categories': categories,
        'sub_categories': sub_categories,
        'groups': groups,
        'products': products,
        'new_product_form': new_product_form,
        'new_colorfamily_form': new_colorfamily_form,
        'conversations': conversations,
    }
    return render(request, 'add_new_pages/new_product.html', context)

@login_required
def new_brand(request, pk, id):
    banners = Banner.objects.all() 
    categories = Category.objects.all() 
    sub_categories = SubCategory.objects.all() 
    groups = Group.objects.all() 
    products = Product.objects.filter(created_by=request.user).filter(is_sold=False) 
    conversations = Conversation.objects.filter(reciever=request.user)
    manage_products = Product.objects.get(id=id)
    brands = Brand.objects.filter(group_id=pk)
    form_group = get_object_or_404(Group, pk=pk)

sell_on_daraz/templates/sell_on_daraz/options.html
<p>Load subCategories</p>
<option value="0"> Please Select </option>
{% for sub_cat in sub_categories %}
<option value="{{ sub_cat.pk }}"> {{ sub_cat.name }} </option>
{% endfor %}

<p>Load Group</p>

{% for group in groups %}
<option value="{{ group.pk }}"> {{ group.name }} </option>
{% endfor %}

sell_on_daraz/templates/sell_on_daraz/sale_on_daraz.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Daraz | {%block title%} {%endblock%}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">

		<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

		<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet" />
		{% tailwind_css %}

		<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
	</head>
	<body class="bg-gray-100 leading-normal tracking-normal ">
		<!-- ................header.................... -->
		{% include 'theme/header.html' %}



		<!-- ......................home...................... -->
		<div class="px-10 lg:px-16 2xl:px-64 mt-3">
			<div id="add_new" class="flex h-[750px] mb-10 rounded-md overflow-hidden bg-[#077eb917]">
                <div id="side_nav" class="w-[400px] h-auto pb-5 border-r-[1px] border-[#01acff] relative">
                    <div class="w-full mt-5 flex flex-col justify-center items-center gap-2 border-b border-[#01acff] pb-1">
                        <img src="/static/assets/icon/user.png" alt="" class="h-20 w-20 rounded-full">
                        <p class="text-xl font-semibold">Hello {{ user.username }} </p>
                    </div>

                    {% url 'sell_on_daraz:new_banner' as banner  %}
                    {% url 'sell_on_daraz:new_category' as cat  %}
                    {% url 'sell_on_daraz:new_sub_category' as sub_cat  %}
                    {% url 'sell_on_daraz:new_groups' as group  %}
                    {% url 'sell_on_daraz:for_sale' as for_sale  %}
                    <div class="flex flex-col divide-y-[1px] divide-[#01aaff65] border-b-[1px] border-[#01aaff65]">
                        <a href="{% url 'sell_on_daraz:new_banner' %}" class="{% if request.path == banner %}active{% endif %} link px-16 py-3 flex justify-between items-center font-semibold text-black/65 text-[16px] hover:text-[#01acff] relative">
                            <p>Banners</p>
                            <p>{{ banners.count }}</p>
                        </a>
                        <a href="{% url 'sell_on_daraz:new_category' %}" class="{% if request.path == cat %}active{% endif %} link px-16 py-3 flex justify-between items-center font-semibold text-black/65 text-[16px] hover:text-[#01acff] relative">
                            <p>Category</p>
                            <p>{{ categories.count }}</p>
                        </a>
                        <a href="{% url 'sell_on_daraz:new_sub_category' %}" class="{% if request.path == sub_cat %}active{% endif %} link px-16 py-3 flex justify-between items-center font-semibold text-black/65 text-[16px] hover:text-[#01acff] relative">
                            <p>Sub Category</p>
                            <p>{{ sub_categories.count }}</p>
                        </a>
                        <a href="{% url 'sell_on_daraz:new_groups' %}" class="{% if request.path == group %}active{% endif %} link px-16 py-3 flex justify-between items-center font-semibold text-black/65 text-[16px] hover:text-[#01acff] relative">
                            <p>Groups</p>
                            <p>{{ groups.count }}</p>
                        </a>
                        <a href="{% url 'sell_on_daraz:for_sale' %}" class="{% if request.path == for_sale %}active{% endif %} link px-16 py-3 flex justify-between items-center font-semibold text-black/65 text-[16px] hover:text-[#01acff] relative">
                            <p>Products</p>
                            <p>{{ products.count }}</p>
                        </a>
                        <a href="{% url 'sell_on_daraz:inbox' 0 %}" class="{% if '/inbox/' in request.path %} active {% endif %} link px-16 py-3 flex justify-between items-center font-semibold text-black/65 text-[16px] hover:text-[#01acff] relative">
                            <p>Inbox</p>
                            <p>{{ conversations.count }}</p>
                        </a>
                    </div>

                    <div class="px-5 absolute bottom-5 w-full ">
                        <a href="{% url 'dashboard:manage_ac' %}" class="">
                            <p class="back text-center font-semibold p-1 bg-[#01aaff3d] hover:bg-[#01acff] hover:text-white  border border-gray-300 rounded-lg focus:ring-[#01aaff] focus:border-[#01aaff3d] w-full flex justify-center items-center">Go to Dashboard</p>
                        </a>
                    </div>
                    
                </div>

                <!-- .............Forms Body............ -->
                <div class="w-full">
                    {% block content %}

					{% endblock %}
                </div>
            </div>
		</div>

		<!-- .................Footer1........................ -->
		{% include 'theme/footer.html' %}
		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
		<script src="https://kit.fontawesome.com/61f0d17e5a.js" crossorigin="anonymous"></script>
	</body>
</html>