daraz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    
    path('', include('mainapp.urls')),
    path('', include('product.urls')),
    path('', include('dashboard.urls')),
    path('seller/', include('sell_on_daraz.urls')),
    path('', include('offer.urls')),
    path('', include('flashsale.urls')),
    path('', include('messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sell_on_daraz/urls.py
from django.urls import path
from . import views

app_name = 'sell_on_daraz'
urlpatterns = [
    path('for_sale/', views.for_sale, name='for_sale'),
    path('inbox/<int:pk>/', views.inbox, name='inbox'),
    path('new_banner/', views.new_banner, name='new_banner'),
    path('new_category/', views.new_category, name='new_category'),
    path('new_sub_category/', views.new_sub_category, name='new_sub_category'),
    path('new_groups/', views.new_groups, name='new_groups'),
    path('new_product/', views.new_product, name='new_product'),
    
    path('<int:pk>/<int:id>/new_brand/', views.new_brand, name='new_brand'),
    path('<int:pk>/<int:id>/new_material/', views.new_material, name='new_material'),
    path('<int:pk>/<int:id>/new_warranty_period/', views.new_warranty_period, name='new_warranty_period'),
    path('<int:pk>/<int:id>/new_listed_year_season/', views.new_listed_year_season, name='new_listed_year_season'),
    path('<int:pk>/<int:id>/new_mens_trend/', views.new_mens_trend, name='new_mens_trend'),
    
    path('load_options/', views.load_options, name='load_options'),
    
    path('banner/<int:pk>/edit/', views.edit_banner, name='edit_banner'),
    path('category/<int:pk>/edit/', views.edit_category, name='edit_category'),
    path('sub_category/<int:pk>/edit/', views.edit_sub_category, name='edit_sub_category'),
    path('group/<int:pk>/edit/', views.edit_group, name='edit_group'),
    path('product/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('product/<int:pk>/manage/', views.manage_product, name='manage_product'),
    
    path('banner/<int:pk>/delete/', views.delete_banner, name='delete_banner'),
    path('category/<int:pk>/delete/', views.delete_category, name='delete_category'),
    path('subcategory/<int:pk>/delete/', views.delete_sub_category, name='delete_sub_category'),
    path('group/<int:pk>/delete/', views.delete_group, name='delete_group'),
    
    path('brand/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_brand, name='delete_brand'),
    path('material/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_material, name='delete_material'),
    path('warranty_period/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_warranty_period, name='delete_warranty_period'),
    path('listed_year_season/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_listed_year_season, name='delete_listed_year_season'),
    path('mens_trend/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_mens_trend, name='delete_mens_trend'),
    
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
]

mainapp/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User


class Banner(models.Model):
    name = models.CharField(max_length=255) 
    image = models.ImageField(upload_to='banner')
    created_by = models.ForeignKey(User, related_name="banner", on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Banners'
        ordering = ['-created_at']
        
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name="category", on_delete = models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['-created_at']
    
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name="sub_category", on_delete = models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Sub Categories'
        ordering = ['-created_at']
    
    def __str__(self):
        return self.name

class Group(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='products/group')
    created_by = models.ForeignKey(User, related_name="group", on_delete = models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Groups'
        ordering = ['-created_at']
        
    def __str__(self):
        return self.name
    

    

product/models.py
from django.db import models
from colorfield.fields import ColorField
from django.contrib.auth.models import User
from mainapp.models import Group, SubCategory, Category

# Create your models here.
class Brand(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    # created_by = models.ForeignKey(User, related_name="brand", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Brand'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class ColorFamily(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    color = ColorField(default='#01acff')
    # created_by = models.ForeignKey(User, related_name="colorfamily", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'ColorFamily'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class SizeName(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    # created_by = models.ForeignKey(User, related_name="size_name", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'SizeName'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class Size(models.Model):
    size_type = models.ForeignKey(SizeName, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    # created_by = models.ForeignKey(User, related_name="size", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Size'
        ordering = ['-created_at']
    def __str__(self):
        return self.name

class Location(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    country_name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="location", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Country Name'
        ordering = ['-created_at']
    def __str__(self):
        return self.country_name
    
class MainMaterial(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="main_material", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Main Material'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class WarrantyType(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="warranty_type", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Warranty Type'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class WarrantyPeriod(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="warranty_period", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Warranty Period'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class ListedYearSeason(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="listed_year_season", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Listed Year Season'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class MensTrend(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="mens_trend", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = "Men's Trend"
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
# group, name, description, price, discount, color_family, image, brand, sku, flash_sale, is_sold
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True)
    color_family = models.ForeignKey(ColorFamily, on_delete=models.SET_NULL, blank=True, null=True)
    size = models.ForeignKey(Size, on_delete=models.SET_NULL, blank=True, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, blank=True, null=True)
    main_material = models.ForeignKey(MainMaterial, on_delete=models.SET_NULL, blank=True, null=True)
    warranty_type = models.ForeignKey(WarrantyType, on_delete=models.SET_NULL, blank=True, null=True)
    warranty_period = models.ForeignKey(WarrantyPeriod, on_delete=models.SET_NULL, blank=True, null=True)
    listed_year_season = models.ForeignKey(ListedYearSeason, on_delete=models.SET_NULL, blank=True, null=True)
    mens_trend = models.ForeignKey(MensTrend, on_delete=models.SET_NULL, blank=True, null=True)
    
    flash_sale = models.BooleanField(default=False, verbose_name = 'Add To FlashSale', null = True)
    wholesale_price = models.BooleanField(default=False, verbose_name = 'Wholesale Price', null = True)
    everyday_low_price = models.BooleanField(default=False, verbose_name = 'Everyday Low Price!', null = True)
    free_delivery = models.BooleanField(default=False, verbose_name = 'Free Delivery', null = True)
    fashion = models.BooleanField(default=False, verbose_name = 'Fashion', null = True)
    beauty_glamour = models.BooleanField(default=False, verbose_name = 'Beauty & Glamour', null = True)
    mart = models.BooleanField(default=False, verbose_name = 'Mart', null = True)
    home_makeover = models.BooleanField(default=False, verbose_name = 'Home Makeover', null = True)
    best_price_guaranteed = models.BooleanField(default=False, verbose_name = 'Best Price Guaranteed', null = True)
    
    name = models.CharField(max_length=400)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField()
    discount = models.DecimalField(max_digits=2,  decimal_places=0)
    discount_price = models.IntegerField(default=0 ,blank=True, null=True)
    sell_price = models.IntegerField(blank = True, null=True)
    image = models.ImageField(upload_to='products/product_images')
    sku = models.CharField(max_length=400, verbose_name = 'SKU')
    is_sold = models.BooleanField(default=False, verbose_name = 'Out Of Stock')
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-created_at']
    
    @property
    def discount_price(self):
        return int(((self.price)*(self.discount))/100)

    @property
    def sell_price(self):
        return (self.price)-(self.discount_price)
    

sell_on_daraz/models.py
from django.db import models

# Create your models here.

sell_on_daraz/templates/edit_pages/edit_banner.html
{% extends 'sell_on_daraz/sale_on_daraz.html' %}
{% load static tailwind_tags %}
{%block title%} Sell on Daraz {%endblock%}

{% block content %}
<!-- ................Edit Products.................. -->
<div id="add_new" class="flex flex-col h-auto mb-10 rounded-md overflow-hidden">
    <!-- .............Forms Body............ -->
    <p class="text-[20px] px-20 py-5 pt-10 font-semibold text-[#01acff]"><a href="{% url 'sell_on_daraz:for_sale' %}" class="hover:text-[#01aaff9d] hover:underline">Sell On Daraz</a> | Edit Banner</p>
    <div class="w-full px-20 pb-10 overflow-auto">
        <div class="w-full h-auto py-16 rounded-lg bg-white flex flex-col justify-center items-center">
            <form action="." method="post" enctype="multipart/form-data" class="h-32 w-full flex justify-center items-center gap-5  rounded-lg relative" >
                {% csrf_token %}
                <div class="h-10 w-[300px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                    <label for="name" class="h-full px-9 font-semibold flex justify-center items-center bg-black text-white">Name</label>
                    {{ edit_banner_form.name }}
                </div>
                <div class="h-10 w-[300px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                    {{ edit_banner_form.image }}
                </div>
                

                {% if banner_form.errors or banner_form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl absolute -bottom-0">
                    {% for field in banner_form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ banner_form.non_field_errors }}
                </div>
                {% endif %}

                <button name="banner_form" type="submit" class="px-12 h-10 font-semibold bg-[#01aaff3d] hover:bg-[#01acff] hover:text-white  border border-gray-300 rounded-lg focus:ring-[#01aaff] focus:border-[#01aaff3d]">UPDATE</button>
                
            </form>
        </div>
    </div>
</div>


{% endblock %}

sell_on_daraz/templates/edit_pages/edit_group.html
{% extends 'sell_on_daraz/sale_on_daraz.html' %}
{% load static tailwind_tags %}
{%block title%} Sell on Daraz {%endblock%}

{% block content %}
<!-- ................Edit Products.................. -->
<div id="add_new" class="flex flex-col h-auto mb-10 rounded-md overflow-hidden ">
    <!-- .............Forms Body............ -->
    <p class="text-[20px] px-20 py-5 pt-10 font-semibold text-[#01acff]"><a href="{% url 'sell_on_daraz:for_sale' %}" class="hover:text-[#01aaff9d] hover:underline">Sell On Daraz</a> | Edit Group</p>
    <div class="w-full px-20 pb-10 overflow-auto">
        <div class="w-full h-auto py-16 rounded-lg bg-white flex flex-col justify-center items-center">
            <form action="." method="post" id="editGroupForm" data-subcategories-url="{% url 'sell_on_daraz:load_options' %}" enctype="multipart/form-data" class="h-52 w-full flex flex-col justify-center items-center gap-5 bg-white rounded-lg relative" >
                {% csrf_token %}
                <div class="grid grid-cols-2 gap-5">
                    <div class="h-10 w-[400px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                        <label for="name" class="h-full w-40 font-semibold flex justify-center items-center bg-black text-white ">Category</label>
                        {{ edit_group_form.category }}
                    </div>
                    <div class="h-10 w-[400px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                        <label for="name" class="h-full w-40 font-semibold flex justify-center items-center bg-black text-white ">SubCategory</label>
                        {{ edit_group_form.subcategory }}
                    </div>
                    <div class="h-10 w-[400px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                        <label for="name" class="h-full w-40 font-semibold flex justify-center items-center bg-black text-white">Name</label>
                        {{ edit_group_form.name }}
                    </div>
                    <div class="h-10 w-[400px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                        {{ edit_group_form.image }}
                    </div>
                </div>
                
                <!-- {% if new_group_form.errors or new_group_form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl absolute -bottom-0">
                    {% for field in new_group_form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ new_group_form.non_field_errors }}
                </div>
                {% endif %} -->
                <button name="group_form" type="submit" class="px-28 h-10 font-semibold bg-[#01aaff3d] hover:bg-[#01acff] hover:text-white  border border-gray-300 rounded-lg focus:ring-[#01aaff] focus:border-[#01aaff3d]">UPDATE</button>
                
            </form>

            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script>
                $("#id_category").change(function () {
                var url = $("#editGroupForm").attr("data-subcategories-url");
                var catId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                    'category': catId
                    },
                    success: function (data) {
                    $("#id_subcategory").html(data);
                    }
                });

                });
            </script>
        </div>
    </div>
</div>


{% endblock %}

sell_on_daraz/templates/edit_pages/manage_product.html
{% extends 'sell_on_daraz/sale_on_daraz.html' %}
{% load static tailwind_tags %}
{%block title%} sell_on_daraz {%endblock%}

{% block content %}
<div class="px-10 py-5 w-full">
    <p class="text-[20px] font-semibold text-[#01acff]">Manage My Products | {{ manage_products.name | slice:":40" }}... </p>
    <div class="h-[650px] mt-5 w-full col-span-3 rounded-md bg-white overflow-hidden relative">
        <!-- ......................manage_product_form....................... -->
        <form action="." method="post" id="manage_product_form">
            {% csrf_token %}
            <div class="h-16 w-full mb-0 flex justify-between items-center px-10 border-b-2 gap-10">
                <p class=" text-black/50 font-semibold cursor-context-menu select-none">
                    <span class="text-sm bg-[#01acff25] px-2 py-[2px] rounded-sm">{{ manage_products.category }}</span> / 
                    <span class="text-sm bg-[#01acff25] px-2 py-[2px] rounded-sm">{{ manage_products.subcategory }}</span> / 
                    <span class="text-sm bg-[#01acff25] px-2 py-[2px] rounded-sm">{{ manage_products.group }}</span>
                </p>
                <div class="w-60 ">{{ manage_product_form.location }}</div>
            </div>
            <div class="h-full w-full flex justify-between items-center divide-x-2 p-5">
                <div class="h-full w-[40%] flex flex-col gap-5 px-5">
                    <div class=" h-full w-full text-black/60 text-sm font-semibold">
                        <div class="w-full flex justify-between items-center">
                            <p>Brand:</p>
                            <a href="{% url 'sell_on_daraz:new_brand' group_id manage_products.id %}" class="hover:text-[#01acff] add_new">Add new +</a>
                        </div>
                        {{ manage_product_form.brand }}
                    </div>
                    <div class=" h-full w-full text-black/60 text-sm font-semibold">
                        <div class="w-full flex justify-between items-center">
                            <p>Main Material:</p>
                            <a href="{% url 'sell_on_daraz:new_material' group_id manage_products.id %}" class="hover:text-[#01acff] add_new">Add new +</a>
                        </div>
                        {{ manage_product_form.main_material }}
                    </div>
                    <div class=" h-full w-full text-black/60 text-sm font-semibold">
                        <div class="w-full flex justify-between items-center">
                            <p>Warranty Type:</p>
                        </div>
                        {{ manage_product_form.warranty_type }}
                    </div>
                    <div class=" h-full w-full text-black/60 text-sm font-semibold">
                        <div class="w-full flex justify-between items-center">
                            <p>Warranty Period:</p>
                            <a href="{% url 'sell_on_daraz:new_warranty_period' group_id manage_products.id %}" class="hover:text-[#01acff] add_new">Add new +</a>
                        </div>
                        {{ manage_product_form.warranty_period }}
                    </div>
                    <div class=" h-full w-full text-black/60 text-sm font-semibold">
                        <div class="w-full flex justify-between items-center">
                            <p>Listed Year Season:</p>
                            <a href="{% url 'sell_on_daraz:new_listed_year_season' group_id manage_products.id %}" class="hover:text-[#01acff] add_new">Add new +</a>
                        </div>
                        {{ manage_product_form.listed_year_season }}
                    </div>
                    <div class=" h-full w-full text-black/60 text-sm font-semibold">
                        <div class="w-full flex justify-between items-center">
                            <p>Mens Trend:</p>
                            <a href="{% url 'sell_on_daraz:new_mens_trend' group_id manage_products.id %}" class="hover:text-[#01acff] add_new">Add new +</a>
                        </div>
                        {{ manage_product_form.mens_trend }}
                    </div>
                </div>
                
                
                <div class="h-full w-[60%] flex flex-col px-5 gap-5">
                    <div class="flex items-center justify-center w-full h-[250px]">
                        <label for="dropzone-file" class="flex flex-col items-center justify-center w-full h-full border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
                            <div class="flex flex-col items-center justify-center pt-5 pb-6">
                                <svg class="w-8 h-8 mb-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"/>
                                </svg>
                                <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold">Click to upload</span> or drag and drop</p>
                                <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG or GIF (MAX. 800x400px)</p>
                            </div>
                            {{ manage_product_form.image }}
                        </label>
                    </div>
                    <div class="w-full h-full px-5 py-5 text-sm text-black/60 grid grid-cols-2">
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.flash_sale }}  <span>Add to Flashsale</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.wholesale_price }} <span>Add to Wholesale Price</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.everyday_low_price }} <span>Add to Everyday Low Price!</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.free_delivery }}  <span>Add to Free Delivery</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.fashion }} <span>Add to Free Fashion</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.beauty_glamour }} <span>Add to Beauty & Glamour</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.mart }}  <span>Add to Mart</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.home_makeover }} <span>Add to Home Makeover</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3">
                            {{ manage_product_form.best_price_guaranteed }} <span>Add to Best Price Guaranteed</span>
                        </div>
                        <div class="flex justify-start items-center py-2 gap-3 text-[#ff0000] font-semibold">
                            {{ manage_product_form.is_sold }} <span>Sold Out</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="h-14 w-full border-t-[2px] bottom-0 absolute">
                <div class="h-full w-full px-10 flex justify-end items-center">
                    <a href="{% url 'sell_on_daraz:for_sale' %}" class="px-5 py-1 rounded-[5px] font-semibold text-black/40 hover:shadow-inner hover:shadow-[#01acff60] hover:bg-[#01acff40]  hover:text-black  transition-all ease-in-out duration-200">CANCEL</a>
                    <button name="manage_product_form" type="submit" class="px-5 py-1 rounded-[5px] font-semibold text-black/40 hover:shadow-inner hover:shadow-[#01acff60] hover:bg-[#01acff40]  hover:text-black  transition-all ease-in-out duration-200">SAVE</button>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}