daraz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    
    path('', include('mainapp.urls')),
    path('', include('product.urls')),
    path('', include('dashboard.urls')),
    path('seller/', include('sell_on_daraz.urls')),
    path('', include('offer.urls')),
    path('', include('flashsale.urls')),
    path('', include('messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    # path('user/dashboard/', views.dashboard, name='dashboard'),
    path('user/manage_ac/', views.manage_ac, name='manage_ac'),
    path('user/my_profile/', views.my_profile, name='my_profile'),
    path('user/inbox/<int:pk>/', views.inbox, name='inbox'),
    path('user/address_book/', views.address_book, name='address_book'),
    path('user/payment_options/', views.payment_options, name='payment_options'),
    path('user/wallet/', views.wallet, name='wallet'),
    path('user/vouchers/', views.vouchers, name='vouchers'),
    path('user/my_orders/', views.my_orders, name='my_orders'),
    path('user/my_returns/', views.my_returns, name='my_returns'),
    path('user/my_cancellations/', views.my_cancellations, name='my_cancellations'),
    path('user/my_reviews/', views.my_reviews, name='my_reviews'),
    path('user/wishlist/', views.wishlist, name='wishlist'),
]

sell_on_daraz/urls.py
from django.urls import path
from . import views

app_name = 'sell_on_daraz'
urlpatterns = [
    path('for_sale/', views.for_sale, name='for_sale'),
    path('inbox/<int:pk>/', views.inbox, name='inbox'),
    path('new_banner/', views.new_banner, name='new_banner'),
    path('new_category/', views.new_category, name='new_category'),
    path('new_sub_category/', views.new_sub_category, name='new_sub_category'),
    path('new_groups/', views.new_groups, name='new_groups'),
    path('new_product/', views.new_product, name='new_product'),
    
    path('<int:pk>/<int:id>/new_brand/', views.new_brand, name='new_brand'),
    path('<int:pk>/<int:id>/new_material/', views.new_material, name='new_material'),
    path('<int:pk>/<int:id>/new_warranty_period/', views.new_warranty_period, name='new_warranty_period'),
    path('<int:pk>/<int:id>/new_listed_year_season/', views.new_listed_year_season, name='new_listed_year_season'),
    path('<int:pk>/<int:id>/new_mens_trend/', views.new_mens_trend, name='new_mens_trend'),
    
    path('load_options/', views.load_options, name='load_options'),
    
    path('banner/<int:pk>/edit/', views.edit_banner, name='edit_banner'),
    path('category/<int:pk>/edit/', views.edit_category, name='edit_category'),
    path('sub_category/<int:pk>/edit/', views.edit_sub_category, name='edit_sub_category'),
    path('group/<int:pk>/edit/', views.edit_group, name='edit_group'),
    path('product/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('product/<int:pk>/manage/', views.manage_product, name='manage_product'),
    
    path('banner/<int:pk>/delete/', views.delete_banner, name='delete_banner'),
    path('category/<int:pk>/delete/', views.delete_category, name='delete_category'),
    path('subcategory/<int:pk>/delete/', views.delete_sub_category, name='delete_sub_category'),
    path('group/<int:pk>/delete/', views.delete_group, name='delete_group'),
    
    path('brand/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_brand, name='delete_brand'),
    path('material/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_material, name='delete_material'),
    path('warranty_period/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_warranty_period, name='delete_warranty_period'),
    path('listed_year_season/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_listed_year_season, name='delete_listed_year_season'),
    path('mens_trend/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_mens_trend, name='delete_mens_trend'),
    
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from mainapp.models import Category

from product.models import Product
from messaging.models import Conversation, ConversationMessage
from messaging.forms import ConversationMessageForm

# Create your views here.
# global variables................
categories = Category.objects.all()
context = {
    'categories': categories,
}


@login_required
def manage_ac(request):
    return render(request, 'pages/manage_account.html', context)

@login_required
def my_profile(request):
    return render(request, 'pages/my_profile.html', context)

@login_required
def inbox(request, pk):
    categories = Category.objects.all()
    sender=request.user
    conversations = Conversation.objects.filter(sender=request.user)
    if pk>0:
        this_conversation = Conversation.objects.get(id=pk)
    else:
        this_conversation = Conversation.objects.none()
    messages = ConversationMessage.objects.filter(conversation_id=pk)
    form = ConversationMessageForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=False) 
            form.instance.conversation=get_object_or_404(Conversation, pk=pk)
            form.instance.created_by=request.user
            form.save()
            return redirect('.')
    else:
        form = ConversationMessageForm()
        
    context={
        'categories': categories,
        'form': form,
        'messages': messages,
        'pk': pk,
        'sender': sender,
        'conversations': conversations,
        'this_conversation': this_conversation,
    }
    return render(request, 'pages/inbox.html', context)

@login_required
def address_book(request):
    return render(request, 'pages/address_book.html', context)

@login_required
def payment_options(request):
    return render(request, 'pages/my_payment_options.html', context)

@login_required
def wallet(request):
    return render(request, 'pages/daraz_wallet.html', context)

@login_required
def vouchers(request):
    return render(request, 'pages/vouchers.html', context)

@login_required
def my_orders(request):
    return render(request, 'pages/my_orders.html', context)

@login_required
def my_returns(request):
    return render(request, 'pages/my_returns.html', context)

@login_required
def my_cancellations(request):
    return render(request, 'pages/my_cancellations.html', context)

@login_required
def my_reviews(request):
    return render(request, 'pages/my_reviews.html', context)

@login_required
def wishlist(request):
    return render(request, 'pages/wishlist.html', context)

dashboard/templates/dashboard/dashboard.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Daraz | {%block title%} {%endblock%}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">

		<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

		<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet" />
		{% tailwind_css %}

		<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
		<script src="https://unpkg.com/htmx.org@1.9.10" integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous"></script>
	</head>
	<body class="bg-gray-100 leading-normal tracking-normal ">
		<!-- ................header.................... -->
		{% include 'theme/header.html' %}


		<!-- ......................home...................... -->
		{% url 'dashboard:manage_ac' as manage_ac  %}
		{% url 'dashboard:my_profile' as my_profile  %}
		{% url 'dashboard:address_book' as address_book  %}
		{% url 'dashboard:payment_options' as payment_options  %}
		{% url 'dashboard:wallet' as wallet  %}
		{% url 'dashboard:vouchers' as vouchers  %}
		{% url 'dashboard:my_orders' as my_orders  %}
		{% url 'dashboard:my_returns' as my_returns  %}
		{% url 'dashboard:my_cancellations' as my_cancellations  %}
		{% url 'dashboard:my_reviews' as my_reviews  %}
		{% url 'dashboard:wishlist' as wishlist  %}
		<div class="px-10 lg:px-16 2xl:px-64 mt-3">
			<div id="dashboard" class="flex h-[750px] mb-10 rounded-md overflow-hidden bg-[#077eb917]">
				<div id="side_nav" class="w-[400px] h-auto pb-5 border-r-[1px] border-[#01acff]">
					<div class="w-full mt-5 flex flex-col justify-center items-center gap-2 border-b border-[#01acff] pb-1">
						<img src="/static/assets/icon/user.png" alt="" class="h-20 w-20 rounded-full">
						<p class="text-xl font-semibold">Hello {{ user.username }} </p>
					</div>
					<div class="px-10 pt-3 text-black/65">
						<a id="{% url 'dashboard:manage_ac' %}" href="{% url 'dashboard:manage_ac' %}" class="{% if request.path == manage_ac %}active{% endif %} font-semibold text-[16px] hover:text-[#01acff] ">Manage My Account</a>
						<div class="ps-3 flex flex-col">
							<a href="{% url 'dashboard:my_profile' %}" class="{% if request.path == my_profile %}active{% endif %} hover:text-[#01acff] hover:underline">My Profile</a>
							<a href="{% url 'dashboard:inbox' 0 %}" class="{% if '/inbox/' in request.path %} active {% endif %} hover:text-[#01acff] hover:underline">Inbox</a>
							<a href="{% url 'dashboard:address_book' %}" class="{% if request.path == address_book %}active{% endif %} hover:text-[#01acff] hover:underline">Address Book</a>
							<a href="{% url 'dashboard:payment_options' %}" class="{% if request.path == payment_options %}active{% endif %} hover:text-[#01acff] hover:underline">My Payment Options</a>
							<a href="{% url 'dashboard:wallet' %}" class="{% if request.path == wallet %}active{% endif %} hover:text-[#01acff] hover:underline">Daraz Wallet</a>
							<a href="{% url 'dashboard:vouchers' %}" class="{% if request.path == vouchers %}active{% endif %} hover:text-[#01acff] hover:underline">Vouchers</a>
						</div>
					</div>
					<div class="px-10 pt-3 text-black/65">
						<a href="{% url 'dashboard:my_orders' %}" class="{% if request.path == my_orders %}active{% endif %} font-semibold text-[16px] hover:text-[#01acff]">My Orders</a>
						<div class="ps-3 flex flex-col text-black/65">
							<a href="{% url 'dashboard:my_returns' %}" class="{% if request.path == my_returns %}active{% endif %} hover:text-[#01acff] hover:underline">My Returns</a>
							<a href="{% url 'dashboard:my_cancellations' %}" class="{% if request.path == my_cancellations %}active{% endif %} hover:text-[#01acff] hover:underline">My Cancellations</a>
						</div>
					</div>
					<div class="px-10 pt-3">
						<a href="{% url 'dashboard:my_reviews' %}" class="{% if request.path == my_reviews %}active{% endif %} font-semibold text-[16px] hover:underline text-black/65 hover:text-[#01acff]">My Reviews</a>
					</div>
					<div class="px-10 pt-3">
						<a href="{% url 'dashboard:wishlist' %}" class="{% if request.path == wishlist %}active{% endif %} font-semibold text-[16px] hover:underline text-black/65 hover:text-[#01acff]">My Wishlist & <br> Followed Stores</a>
					</div>
					<div class="px-10 pt-10">
						<a id="sale" href="{% url 'sell_on_daraz:for_sale' %}" class=" font-bold text-[16px] hover:underline text-[#ff01014b] hover:text-[#01aaff81]">Sell On Daraz</a>
					</div>
				</div>

				<!-- .............Dashboard Body............ -->
				<div class="w-full h-full">
					{% block content %}

					{% endblock %}
				</div>

				<!-- <script>
					$("#dashboard #side_nav a").on("click", function(){
							$("#dashboard #side_nav a").removeClass("active");
							$(this).addClass("active");
						})
				</script> -->
			</div>

			
		</div>

		

		<!-- .................Footer1........................ -->
		{% include 'theme/footer.html' %}
		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
		<script src="https://kit.fontawesome.com/61f0d17e5a.js" crossorigin="anonymous"></script>

	</body>
</html>