daraz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    
    path('', include('mainapp.urls')),
    path('', include('product.urls')),
    path('', include('dashboard.urls')),
    path('seller/', include('sell_on_daraz.urls')),
    path('', include('offer.urls')),
    path('', include('flashsale.urls')),
    path('', include('messaging.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views
app_name = 'product'
urlpatterns = [
    path('products/', views.products, name='products'),
    path('filters/', views.filters, name='filters'),
    path('products/<int:product_id>/', views.details, name='details'),
]

sell_on_daraz/urls.py
from django.urls import path
from . import views

app_name = 'sell_on_daraz'
urlpatterns = [
    path('for_sale/', views.for_sale, name='for_sale'),
    path('inbox/<int:pk>/', views.inbox, name='inbox'),
    path('new_banner/', views.new_banner, name='new_banner'),
    path('new_category/', views.new_category, name='new_category'),
    path('new_sub_category/', views.new_sub_category, name='new_sub_category'),
    path('new_groups/', views.new_groups, name='new_groups'),
    path('new_product/', views.new_product, name='new_product'),
    
    path('<int:pk>/<int:id>/new_brand/', views.new_brand, name='new_brand'),
    path('<int:pk>/<int:id>/new_material/', views.new_material, name='new_material'),
    path('<int:pk>/<int:id>/new_warranty_period/', views.new_warranty_period, name='new_warranty_period'),
    path('<int:pk>/<int:id>/new_listed_year_season/', views.new_listed_year_season, name='new_listed_year_season'),
    path('<int:pk>/<int:id>/new_mens_trend/', views.new_mens_trend, name='new_mens_trend'),
    
    path('load_options/', views.load_options, name='load_options'),
    
    path('banner/<int:pk>/edit/', views.edit_banner, name='edit_banner'),
    path('category/<int:pk>/edit/', views.edit_category, name='edit_category'),
    path('sub_category/<int:pk>/edit/', views.edit_sub_category, name='edit_sub_category'),
    path('group/<int:pk>/edit/', views.edit_group, name='edit_group'),
    path('product/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('product/<int:pk>/manage/', views.manage_product, name='manage_product'),
    
    path('banner/<int:pk>/delete/', views.delete_banner, name='delete_banner'),
    path('category/<int:pk>/delete/', views.delete_category, name='delete_category'),
    path('subcategory/<int:pk>/delete/', views.delete_sub_category, name='delete_sub_category'),
    path('group/<int:pk>/delete/', views.delete_group, name='delete_group'),
    
    path('brand/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_brand, name='delete_brand'),
    path('material/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_material, name='delete_material'),
    path('warranty_period/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_warranty_period, name='delete_warranty_period'),
    path('listed_year_season/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_listed_year_season, name='delete_listed_year_season'),
    path('mens_trend/<int:pk>/<int:id1>/<int:id2>/delete/', views.delete_mens_trend, name='delete_mens_trend'),
    
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
]

mainapp/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User


class Banner(models.Model):
    name = models.CharField(max_length=255) 
    image = models.ImageField(upload_to='banner')
    created_by = models.ForeignKey(User, related_name="banner", on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Banners'
        ordering = ['-created_at']
        
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name="category", on_delete = models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['-created_at']
    
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name="sub_category", on_delete = models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Sub Categories'
        ordering = ['-created_at']
    
    def __str__(self):
        return self.name

class Group(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='products/group')
    created_by = models.ForeignKey(User, related_name="group", on_delete = models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'Groups'
        ordering = ['-created_at']
        
    def __str__(self):
        return self.name
    

    

product/models.py
from django.db import models
from colorfield.fields import ColorField
from django.contrib.auth.models import User
from mainapp.models import Group, SubCategory, Category

# Create your models here.
class Brand(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    # created_by = models.ForeignKey(User, related_name="brand", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Brand'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class ColorFamily(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    color = ColorField(default='#01acff')
    # created_by = models.ForeignKey(User, related_name="colorfamily", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'ColorFamily'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class SizeName(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    # created_by = models.ForeignKey(User, related_name="size_name", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'SizeName'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class Size(models.Model):
    size_type = models.ForeignKey(SizeName, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    # created_by = models.ForeignKey(User, related_name="size", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Size'
        ordering = ['-created_at']
    def __str__(self):
        return self.name

class Location(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    country_name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="location", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Country Name'
        ordering = ['-created_at']
    def __str__(self):
        return self.country_name
    
class MainMaterial(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="main_material", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Main Material'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class WarrantyType(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="warranty_type", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Warranty Type'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class WarrantyPeriod(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="warranty_period", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Warranty Period'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class ListedYearSeason(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="listed_year_season", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Listed Year Season'
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
class MensTrend(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)
    # created_by = models.ForeignKey(User, related_name="mens_trend", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        verbose_name_plural = "Men's Trend"
        ordering = ['-created_at']
    def __str__(self):
        return self.name
    
# group, name, description, price, discount, color_family, image, brand, sku, flash_sale, is_sold
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True)
    color_family = models.ForeignKey(ColorFamily, on_delete=models.SET_NULL, blank=True, null=True)
    size = models.ForeignKey(Size, on_delete=models.SET_NULL, blank=True, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, blank=True, null=True)
    main_material = models.ForeignKey(MainMaterial, on_delete=models.SET_NULL, blank=True, null=True)
    warranty_type = models.ForeignKey(WarrantyType, on_delete=models.SET_NULL, blank=True, null=True)
    warranty_period = models.ForeignKey(WarrantyPeriod, on_delete=models.SET_NULL, blank=True, null=True)
    listed_year_season = models.ForeignKey(ListedYearSeason, on_delete=models.SET_NULL, blank=True, null=True)
    mens_trend = models.ForeignKey(MensTrend, on_delete=models.SET_NULL, blank=True, null=True)
    
    flash_sale = models.BooleanField(default=False, verbose_name = 'Add To FlashSale', null = True)
    wholesale_price = models.BooleanField(default=False, verbose_name = 'Wholesale Price', null = True)
    everyday_low_price = models.BooleanField(default=False, verbose_name = 'Everyday Low Price!', null = True)
    free_delivery = models.BooleanField(default=False, verbose_name = 'Free Delivery', null = True)
    fashion = models.BooleanField(default=False, verbose_name = 'Fashion', null = True)
    beauty_glamour = models.BooleanField(default=False, verbose_name = 'Beauty & Glamour', null = True)
    mart = models.BooleanField(default=False, verbose_name = 'Mart', null = True)
    home_makeover = models.BooleanField(default=False, verbose_name = 'Home Makeover', null = True)
    best_price_guaranteed = models.BooleanField(default=False, verbose_name = 'Best Price Guaranteed', null = True)
    
    name = models.CharField(max_length=400)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField()
    discount = models.DecimalField(max_digits=2,  decimal_places=0)
    discount_price = models.IntegerField(default=0 ,blank=True, null=True)
    sell_price = models.IntegerField(blank = True, null=True)
    image = models.ImageField(upload_to='products/product_images')
    sku = models.CharField(max_length=400, verbose_name = 'SKU')
    is_sold = models.BooleanField(default=False, verbose_name = 'Out Of Stock')
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-created_at']
    
    @property
    def discount_price(self):
        return int(((self.price)*(self.discount))/100)

    @property
    def sell_price(self):
        return (self.price)-(self.discount_price)
    

sell_on_daraz/models.py
from django.db import models

# Create your models here.

sell_on_daraz/templates/add_new_pages/for_sale.html
{% extends 'sell_on_daraz/sale_on_daraz.html' %}
{% load static tailwind_tags %}
{%block title%} sell_on_daraz {%endblock%}

{% block content %}
<div class="px-10 py-5 w-full">
    <p class="text-[20px] font-semibold text-[#01acff]">Sell On Daraz | My Products</p>
    <div class="w-full h-5 mt-4">
        <div class="h-auto w-full col-span-3 rounded-md py-4 bg-white">
            <div id="my_product" class="px-4 pb-3 bg-white flex justify-between items-center">
                <p id="product_list_title" class="title text-lg font-semibold">My Products</p>
                <a href="{% url 'sell_on_daraz:new_product' %}" class="link px-5 py-2 border-[1px] rounded-md hover:bg-black/5 font-semibold text-[#01acff] hover:text-[#f00] ">Add Product +</a>
            </div>
            <div id="on_click" class="h-[570px] relative overflow-auto">
                <!-- ................My Product List.............. -->
                <div class="pb-36">
                    <div class="flex justify-evenly items-center w-full h-12  bg-gray-100 sticky top-0 font-semibold z-40">
                        <div class="w-[350px] ps-4">Name</div>
                        <div class="w-[17%] flex justify-center items-center">Created At</div>
                        <div class="w-[17%] flex justify-center items-center">Items</div>
                        <div class="w-[17%] flex justify-center items-center">Total Sells</div>
                        <div class="w-[10%] flex justify-center items-center">Manage</div>
                    </div>
                    {% for product in products %}
                    <div class="flex justify-evenly items-center w-full h-12 border-b-[1px] border-[#01acff32] hover:bg-[#01acff12]">
                        <div class="w-[350px] ps-4 line-clamp-1"> {{ product.name }} </div>
                        <div class="w-[17%] flex justify-center items-center">{{ product.created_at.date }}</div>
                        <div class="w-[17%] flex justify-center items-center"><img src="{{ product.image.url }}" alt="" class="h-10 w-10"></div>
                        <div class="w-[17%] flex justify-center items-center">{{ product.price }}</div>
                        <div class="w-[10%] flex justify-center items-center relative">
                            <button class="group z-10 p-2 text-sm font-medium text-center text-black rounded-lg hover:bg-[#01acff20]">
                                <svg class="w-4 h-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 4 15">
                                    <path d="M3.5 1.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm0 6.041a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm0 5.959a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z"/>
                                </svg>
                                <div class="hidden group-hover:block z-10 bg-white divide-y divide-gray-100 rounded-lg shadow shadow-[#01acff70] w-28 absolute right-[67px] top-2">
                                    <ul class="py-2 text-sm text-start text-gray-700" aria-labelledby="dropdownMenuIconButton">
                                        <li>
                                            <a href="{% url 'sell_on_daraz:edit_product' product.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Edit</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'product:details' product.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Details</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'sell_on_daraz:manage_product' product.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Manage</a>
                                        </li>
                                        <li>
                                            <!-- <a href="{% url 'sell_on_daraz:delete_product' product.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Delete</a> -->
                                            <form id="delete-product-form" action="{% url 'sell_on_daraz:delete_product' product.id %}" method="post">
                                                {% csrf_token %}
                                                <input name="delete_product" type="submit" value="Delete" class="block w-full text-start px-4 py-2 hover:bg-[#01acff50]" onclick="return confirmDelete();">
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                            </button>
                        </div>
                    </div>
                    {% endfor %}
                    {% for product in sold_products %}
                    <div class="flex justify-evenly items-center w-full h-12 border-b-[1px] border-[#01acff32] hover:bg-[#ff00002c]  bg-[#ff00001c] text-[#ff000079]">
                        <div class="w-[350px] ps-4 line-clamp-1"> {{ product.name }} </div>
                        <div class="w-[17%] flex justify-center items-center">{{ product.created_at.date }}</div>
                        <div class="w-[17%] flex justify-center items-center"><img src="{{ product.image.url }}" alt="" class="h-10 w-10"></div>
                        <div class="w-[17%] flex justify-center items-center">{{ product.price }}</div>
                        <div class="w-[10%] flex justify-center items-center relative">
                            <button class="group z-10 p-2 text-sm font-medium text-center text-black rounded-lg hover:bg-[#01acff20]">
                                <svg class="w-4 h-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 4 15">
                                    <path d="M3.5 1.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm0 6.041a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm0 5.959a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z"/>
                                </svg>
                                <div class="hidden group-hover:block z-10 bg-white divide-y divide-gray-100 rounded-lg shadow shadow-[#01acff70] w-28 absolute right-[67px] top-2">
                                    <ul class="py-2 text-sm text-start text-gray-700" aria-labelledby="dropdownMenuIconButton">
                                        <li>
                                            <a href="{% url 'sell_on_daraz:edit_product' product.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Edit</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'product:details' product.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Details</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'sell_on_daraz:manage_product' product.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Manage</a>
                                        </li>
                                        <li>
                                            <!-- <a href="{% url 'sell_on_daraz:delete_product' product.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Delete</a> -->
                                            <form action="{% url 'sell_on_daraz:delete_product' product.id %}" method="post">
                                                {% csrf_token %}
                                                <input name="delete_product" type="submit" value="Delete" class="block w-full text-start px-4 py-2 hover:bg-[#01acff50]" onclick="return confirmDelete();">
                                            </form>
                                        </li>
                                    </ul>
                                </div>
                            </button>
                        </div>
                        
                    </div>
                    {% endfor %}
                </div>
                <script>
                    function confirmDelete() {
                        return confirm("Are you sure you want to delete this product?");
                    }
                </script>
            </div>
        </div>
    </div>
</div>
{% endblock %}

sell_on_daraz/templates/add_new_pages/groups.html
{% extends 'sell_on_daraz/sale_on_daraz.html' %}
{% load static tailwind_tags %}
{%block title%} sell_on_daraz {%endblock%}

{% block content %}
<div class="px-10 py-5 w-full">
    <p class="text-[20px] font-semibold text-[#01acff]">Sell On Daraz | Product Groups</p>
    <div class="w-full mt-4 flex flex-col gap-5">

        
        <form action="." method="post" id="newGroupForm" data-subcategories-url="{% url 'sell_on_daraz:load_options' %}" enctype="multipart/form-data" class="h-52 w-full flex flex-col justify-center items-center gap-5 bg-white rounded-lg relative" >
            {% csrf_token %}
            <div class="grid grid-cols-2 gap-5">
                <div class="h-10 w-[400px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                    <label for="name" class="h-full w-40 font-semibold flex justify-center items-center bg-black text-white">Category</label>
                    {{ new_group_form.category }}
                </div>
                <div class="h-10 w-[400px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                    <label for="name" class="h-full w-40 font-semibold flex justify-center items-center bg-black text-white ">SubCategory</label>
                    {{ new_group_form.subcategory }}
                </div>
                <div class="h-10 w-[400px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                    <label for="name" class="h-full w-40 font-semibold flex justify-center items-center bg-black text-white">Name</label>
                    {{ new_group_form.name }}
                </div>
                <div class="h-10 w-[400px] p-0 m-0 text-sm flex justify-center items-center border-[1px] rounded-lg overflow-hidden bg-transparent">
                    {{ new_group_form.image }}
                </div>
            </div>
            
            

            <!-- {% if new_group_form.errors or new_group_form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl absolute -bottom-0">
                {% for field in new_group_form %}
                    {{ field.errors }}
                {% endfor %}
                {{ new_group_form.non_field_errors }}
            </div>
            {% endif %} -->


            <button name="new_group_form" type="submit" class="px-28 h-10 font-semibold bg-[#01aaff3d] hover:bg-[#01acff] hover:text-white  border border-gray-300 rounded-lg focus:ring-[#01aaff] focus:border-[#01aaff3d]">ADD</button>
            
        </form>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $("#id_category").change(function () {
            var url = $("#newGroupForm").attr("data-subcategories-url");
            var catId = $(this).val();

            $.ajax({
                url: url,
                data: {
                'category': catId
                },
                success: function (data) {
                $("#id_subcategory").html(data);
                }
            });

            });
        </script>

        
        <div class="w-full bg-white rounded-lg ">
            <div class="px-10 flex justify-between items-center">
                <p class="text-2xl py-4  text-[#01acff]">Product Groups</p>
                <!-- <select name="Filter" id="" class="h-8 w-40 py-0 px-3 flex justify-center items-center">
                    <option value="0">All Groups</option>
                    {% for sub_cat in sub_categories %}
                    <option value="{{ sub_cat.id }}"> {{ sub_cat.name }} </option>
                    {% endfor %}
                </select> -->
            </div>
            <!-- ...................Product Groups................... -->
            <ul class="h-[370px] w-full grid grid-cols-2 content-start gap-3 pt-1 pb-36 px-10 overflow-auto">
                {% for group in groups %}
                <li class="w-full h-12 bg-[#01aaff0c] shadow shadow-[#01aaff49] pe-5 rounded-md flex justify-between items-center font-semibold">
                    <div class="p-[1px] h-full w-full flex justify-start items-center gap-4 overflow-hidden">
                        <img src="{{ group.image.url }}" alt="" class="h-full w-10 rounded-md border-[2px]">
                        <div>{{ group.name }}</div>
                    </div>
                    <div class="flex justify-center items-center relative">
                        <button class="group inline-flex self-center items-start p-2 text-sm font-medium text-center text-black rounded-lg hover:bg-[#01acff50]">
                            <svg class="w-4 h-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 4 15">
                                <path d="M3.5 1.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm0 6.041a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Zm0 5.959a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z"/>
                            </svg>
                            <div class="hidden group-hover:block z-10 bg-white divide-y divide-gray-100 rounded-lg shadow shadow-[#01acff70] w-28 absolute right-[33px] top-3">
                                <ul class="py-2 text-sm text-start text-gray-700" aria-labelledby="dropdownMenuIconButton">
                                    <li>
                                        <a href="{% url 'sell_on_daraz:edit_group' group.id %}" class="block px-4 py-2 hover:bg-[#01acff50]">Edit</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'product:filters' %}?group={{ group.id }}&name={{ group.name }}" class="block px-4 py-2 hover:bg-[#01acff50]">Go to</a>
                                    </li>
                                    <li>
                                        <form action="{% url 'sell_on_daraz:delete_group' group.id %}" method="post">
                                            {% csrf_token %}
                                            <input name="delete_group" type="submit" value="Delete" class="block w-full text-start px-4 py-2 hover:bg-[#01acff50]" onclick="return confirmDelete();">
                                        </form>

                                        <script>
                                            function confirmDelete() {
                                                return confirm("Are you sure you want to delete this Group?");
                                            }
                                        </script>
                                    </li>
                                </ul>
                            </div>
                        </button>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}